substitutions:
  _IMG_KEEP: "2"
steps:
  # delete docker image
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        images="tsunglin00"
        for image in ${images[@]}; do
          echo "Cleaning image ${image}"
          c=0
          image="gcr.io/$PROJECT_ID/${image}"
          number_keep_images=${_IMG_KEEP}
          date=$(gcloud container images list-tags gcr.io/macro-resource-353407/tsunglin00 --limit=1 --sort-by=~TIMESTAMP --format='get(timestamp[datetime])')
          echo "date ${date} image ${image}"
          for digest in $(gcloud container images list-tags $image --limit=unlimited --sort-by=~TIMESTAMP --filter="timestamp.datetime < '${date}'" --format='get(digest)'); do
            (
                set -x
                echo "${image}@${digest}" >&2
                echo "a ${number_keep_images} ${c} ${date}"
                gcloud container images delete -q --force-delete-tags "${image}@${digest}"
            )
            c=c+1
          done
          echo "Deleted ${c} images for ${image}." >&2
        done
  # mvn Build
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/macro-resource-353407/tsunglin00:latest', '.']
  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/macro-resource-353407/tsunglin00:latest']
  # patch kubernetes deployment to trigger rolling update
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - set
      - image
      - deployment
      - jenkins-k8s-deployment
      - jenkins-k8s=gcr.io/macro-resource-353407/tsunglin00:latest
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-d'
      - 'CLOUDSDK_CONTAINER_CLUSTER=jenkins-ci-cd'
  # deployment restart
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["rollout", "restart", "deployment/jenkins-k8s-deployment"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-east1-d"
      - "CLOUDSDK_CONTAINER_CLUSTER=jenkins-ci-cd"
