apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8s-deployment
  labels:
    app: jenkins-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-k8s
  template:
    metadata:
      labels:
        app: jenkins-k8s
    spec:
      containers:
        - name: jenkins-k8s
          image: gcr.io/macro-resource-353407/tsunglin00:latest
          imagePullPolicy: Always
          env:
            - name: "PORT"
              value: "28019"
